name: EOL ROS2 installers test
on:
  push:
    branches:
      - main
    paths:
      - "ros2-dashing-**.sh"
      - "ros2-eloquent-**.sh"
      - "ros2-galactic-**.sh"
      - ".github/workflows/eol-installers.yml"
  pull_request:
    branches:
      - main
    paths:
      - "ros2-dashing-**.sh"
      - "ros2-eloquent-**.sh"
      - "ros2-galactic-**.sh"
      - ".github/workflows/eol-installers.yml"
  schedule:
    - cron: "0 1 * * 1"

jobs:
  # os-check-on-ubuntu-bionic:
  #   runs-on: ubuntu-18.04
  #   steps:
  #     - uses: actions/checkout@v3
  #       with:
  #         submodules: recursive
  #     - name: Run bats test
  #       run: |
  #         ./.test/bats/bin/bats ./.test/test-os-check-bionic.bats

  # dashing-ros-base-main:
  #   runs-on: ubuntu-18.04
  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: Run the install script
  #       run: |
  #         ./ros2-dashing-ros-base-main.sh
  #     - name: Run the test script
  #       run: |
  #         sed -e 's/^\(ROS_DISTRO=.*\)/#\1\nROS_DISTRO=dashing/g' -i tutorial.sh
  #         sed -e 's/^\(source \/opt.*bash\)$/\1\nrosdep install -r -y -i --from-paths ./g' -i tutorial.sh
  #         bash <(head -n -2 ./tutorial.sh)

  # dashing-desktop-main:
  #   runs-on: ubuntu-18.04
  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: Run the install script
  #       run: |
  #         ./ros2-dashing-desktop-main.sh
  #     - name: Run the test script
  #       run: |
  #         sed -e 's/^\(ROS_DISTRO=.*\)/#\1\nROS_DISTRO=dashing/g' -i tutorial.sh
  #         bash <(head -n -2 ./tutorial.sh)

  # eloquent-ros-base-main:
  #   runs-on: ubuntu-18.04
  #   if: contains(github.event.head_commit.message, '[skip ci]') == false
  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: Run the install script
  #       run: |
  #         ./ros2-eloquent-ros-base-main.sh
  #     - name: Run the test script
  #       run: |
  #         sed -e 's/^\(ROS_DISTRO=.*\)/#\1\nROS_DISTRO=eloquent/g' -i tutorial.sh
  #         sed -e 's/^\(source \/opt.*bash\)$/\1\nrosdep install -r -y -i --from-paths ./g' -i tutorial.sh
  #         bash <(head -n -2 ./tutorial.sh)

  # eloquent-desktop-main:
  #   runs-on: ubuntu-18.04
  #   if: contains(github.event.head_commit.message, '[skip ci]') == false
  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: Run the install script
  #       run: |
  #         ./ros2-eloquent-desktop-main.sh
  #     - name: Run the test script
  #       run: |
  #         sed -e 's/^\(ROS_DISTRO=.*\)/#\1\nROS_DISTRO=eloquent/g' -i tutorial.sh
  #         bash <(head -n -2 ./tutorial.sh)

  galactic-ros-base-main:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Run the install script
        run: |
          ./ros2-galactic-ros-base-main.sh
      - name: Run the test script
        run: |
          sed -e 's/^\(ROS_DISTRO=.*\)/#\1\nROS_DISTRO=galactic/g' -i tutorial.sh
          sed -e 's/^\(source \/opt.*bash\)$/\1\nrosdep install -r -y -i --from-paths ./g' -i tutorial.sh
          bash <(head -n -2 ./tutorial.sh)

  galactic-desktop-main:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Run the install script
        run: |
          ./ros2-galactic-desktop-main.sh
      - name: Run the test script
        run: |
          sed -e 's/^\(ROS_DISTRO=.*\)/#\1\nROS_DISTRO=galactic/g' -i tutorial.sh
          bash <(head -n -2 ./tutorial.sh)
