name: ROS2 installers test
on:
  push:
    branches:
      - main
    paths:
      - "ros2-humble-**.sh"
      - ".github/workflows/installers.yml"
  pull_request:
    branches:
      - main
    paths:
      - "ros2-humble-**.sh"
      - ".github/workflows/installers.yml"
  schedule:
    - cron: "0 1 * * 1"

jobs:
  os-check-on-ubuntu-jammy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Run bats test
        run: |
          ./.test/bats/bin/bats ./.test/test-os-check-jammy.bats

  humble-ros-base-main:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Run the install script
        run: |
          ./ros2-humble-ros-base-main.sh
      - name: Run the test script
        run: |
          sed -e 's/^\(ROS_DISTRO=.*\)/#\1\nROS_DISTRO=humble/g' -i tutorial.sh
          sed -e 's/^\(source \/opt.*bash\)$/\1\nrosdep install -r -y -i --from-paths ./g' -i tutorial.sh
          bash <(head -n -2 ./tutorial.sh)

  humble-desktop-main:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Run the install script
        run: |
          ./ros2-humble-desktop-main.sh
      - name: Run the test script
        run: |
          sed -e 's/^\(ROS_DISTRO=.*\)/#\1\nROS_DISTRO=humble/g' -i tutorial.sh
          bash <(head -n -2 ./tutorial.sh)

  iron-ros-base-main:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Run the install script
        run: |
          ./ros2-iron-ros-base-main.sh
      - name: Run the test script
        run: |
          sed -e 's/^\(ROS_DISTRO=.*\)/#\1\nROS_DISTRO=iron/g' -i tutorial.sh
          sed -e 's/^\(source \/opt.*bash\)$/\1\nrosdep install -r -y -i --from-paths ./g' -i tutorial.sh
          bash <(head -n -2 ./tutorial.sh)

  iron-desktop-main:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Run the install script
        run: |
          ./ros2-iron-desktop-main.sh
      - name: Run the test script
        run: |
          sed -e 's/^\(ROS_DISTRO=.*\)/#\1\nROS_DISTRO=iron/g' -i tutorial.sh
          bash <(head -n -2 ./tutorial.sh)
